name: Code Quality Check

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  flake8:
    name: Check Code Quality with Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust the Python version as needed
      
      - name: Install dependencies
        run: |
          pip install flake8
      
      - name: Run Flake8
        run: |
          flake8 --exclude=".git,__pycache__,venv" .
