name: Unit Testing

on:
  push:
    branches:
      - test

jobs:
    install:
      runs-on: ubuntu-latest
      steps:
        - name: Git Checkout
          uses: actions/checkout@v2
  
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10.4'
  
        - name: Install dependencies
          run: |
            pip install -r requirement.txt
  
        - name: Run tests
          run: |
            pytest test.py